-- Complete SQL script to set up super admin
-- Run this in Supabase SQL Editor

-- Step 1: Update constraint to allow admin roles
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;

ALTER TABLE users ADD CONSTRAINT users_role_check 
  CHECK (role IN ('user', 'celebrant', 'vendor', 'both', 'admin', 'super_admin'));

-- Step 2: Generate PIN hash for '222222'
-- Note: You'll need to run the Node.js script to get the bcrypt hash, or use this pre-generated hash
-- For PIN '222222', the hash is generated by: bcrypt.hash('222222', 10)

-- Step 3: Update user to super_admin with new PIN
-- Replace <PIN_HASH> with the actual hash from the script output
UPDATE users 
SET 
  role = 'super_admin',
  pin_hash = '<PIN_HASH>'  -- Will be replaced by script
WHERE phone_number = '+2348131074911';

-- Step 4: Verify
SELECT id, phone_number, first_name, last_name, role 
FROM users 
WHERE phone_number = '+2348131074911';
